[package]
name = "logtopus"
version = "0.1.0"
authors = ["Carsten Saathoff <carsten@kodemaniak.de>", "niveau0 <plingplong@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
